KillerAppS2/Models/ErrorViewModel.cs
using System;

namespace KillerAppS2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KillerAppS2/ViewModels/RiddlePageModel.cs
using ServiceLayer.ViewModels.InputViewModels;
using ServiceLayer.ViewModels.OutputViewModels;

namespace KillerAppS2.ViewModel
{ 
    public class RiddlePageModel
    {
        private CategoriesModel categories;
        private AddMessageModel post;
        private RiddlesResultModel get;
        public RiddlePageModel()
        {
            post = new AddMessageModel();
            get = new RiddlesResultModel();
            categories = new CategoriesModel();
        }
        public AddMessageModel Post { get; set; }
        public RiddlesResultModel Get { get; internal set; }
        public CategoriesModel Categories { get; internal set; }
    }
}

KillerAppS2/ViewModels/StartPageModel.cs
using ServiceLayer.ViewModels.OutputViewModels;

namespace PresentationLayer.ViewModels
{
    public class StartPageModel
    {
        public CategoriesModel Categories { get; set; }

        public RiddlesResultModel Riddles { get; set; }
    }
}

KillerAppS2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PresentationLayer.ViewModels;
using ServiceLayer;
using ServiceLayer.Handlers;

namespace KillerAppS2.Controllers
{
    public class HomeController : Controller
    {
        private CategoryHandler categoryHandler;
        private RiddleHandler riddleHandler;

        public HomeController(ServiceLayerBuilder serviceLayerBuilder)
        {
            categoryHandler = serviceLayerBuilder.GetCategoryHandler();
            riddleHandler = serviceLayerBuilder.GetRiddleHandler();
        }
        
        public IActionResult Index()
        {
            return View("StartPage", new StartPageModel() { Categories = categoryHandler.GetAllCategories(), Riddles = riddleHandler.Get5UnsolvedRiddles() });
        }
    }
}

KillerAppS2/Controllers/RiddleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KillerAppS2.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using ServiceLayer.Handlers;
using ServiceLayer.ViewModels;

namespace PresentationLayer.Controllers
{
    public class RiddleController : Controller
    {
        private RiddleHandler riddleHandler;
        private CategoryHandler categoryHandler;

        public RiddleController(ServiceLayerBuilder serviceLayerBuilder)
        {
            riddleHandler = serviceLayerBuilder.GetRiddleHandler();
            categoryHandler = serviceLayerBuilder.GetCategoryHandler();
        }

        public IActionResult Category(string _categoryName)
        {
            return View("RiddlePage", new RiddlePageModel() { Get = riddleHandler.GetRiddlesFromCategory(_categoryName), Categories = categoryHandler.GetAllCategories() });
        }

        [HttpPost]
        public IActionResult PostMessage(RiddlePageModel _rpm)
        {
            if (ModelState.IsValid)
            {
                riddleHandler.PostMessage(_rpm.Post);
                return Redirect(Url.Action("Index", "Home"));
            }
            return Redirect(Url.Action("Index", "Home"));
        }
    }
}

KillerAppS2/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using ServiceLayer.Handlers;
using ServiceLayer.ViewModels.InputViewModels;

namespace PresentationLayer.Controllers
{
    public class UserController : Controller
    {
        private CategoryHandler categoryHandler;
        private UserHandler userHandler;

        public UserController(ServiceLayerBuilder serviceLayerBuilder)
        {
            userHandler = serviceLayerBuilder.GetUserHandler();
            categoryHandler = serviceLayerBuilder.GetCategoryHandler();
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddUser(AddUserModel _aum)
        {
            if (ModelState.IsValid)
            {
                if (_aum.PasswordRepeat == _aum.Password && userHandler.Adduser(_aum))
                {
                    return View("LogIn");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult LogIn(LogInModel _lim)
        {
            if (ModelState.IsValid)
            {
                var resultPair = userHandler.ValidateLoginAttempt(_lim);
                if (resultPair.Object1 == ModelLayer.Structural_Interfaces.LogInResult.Good)
                {
                    HttpContext.Session.SetString("UserID", resultPair.Object2.UserID);
                    HttpContext.Session.SetString("UserName", resultPair.Object2.UserName);
                    return Redirect(Url.Action("Index", "Home"));
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return View();
        }
    }
}

KillerAppS2/Views/Home/Index.cshtml
@model ServiceLayer.InputViewModels.LogInModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @*<div class="_navbar">@Html.Partial("../Shared/_nav")</div>
        <div class="_anouncementsboard">@Html.Partial("../Shared/_announcements")</div>
        <div class="_catagories">@Html.Partial("../Shared/_categories")</div>*@
    <div class="loginContainer">
        <h2>Login</h2>
        <form method="post">
            <input asp-for="Username" class="form-control loginInput">
            <input asp-for="Password" class="form-control loginInput">
            @if (TempData["FailedLoginAttempt"] != null)
            {
                <div class="errorMessage">@TempData["FailedLoginAttempt"]</div>
            }
            <div><input type="submit" value="Login" class="btn loginButton" /></div>
        </form>
    </div>
</body>
</html>

KillerAppS2/Views/Home/StartPage.cshtml
@model PresentationLayer.ViewModels.StartPageModel

@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <style>
        ._categories a {
            margin: 10px 4px 10px 4px;
        }
    </style>
</head>
<body>
    <div class="col-sm-10 _categories" style="margin: auto auto auto 16px; border: 2px solid black; border-radius: 5px 5px; width: 120px;">
        @foreach (var category in Model.Categories.Categories)
        {
            <div class="row">
                <a asp-controller="Riddle" asp-action="Category" asp-route-_categoryName="@category.CategoryName">@category.CategoryName</a>
            </div>
        }
    </div>
    <div class="col-sm-10">
        @foreach (var riddle in Model.Riddles.Riddles)
        {
            <div class="_unsolvedRiddle row" style="border: 2px solid black; margin: 10px 10px 10px 10px; font-size: 40px; display:flex;justify-content:center;align-items:center;">@riddle.RiddleContent</div>
        }
    </div>
</body>
</html>

<script>
    var myIndex = 0;
    SlideShow();

    function SlideShow() {
        var i;
        var x = document.getElementsByClassName("_unsolvedRiddle");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) { myIndex = 1 }
        x[myIndex - 1].style.display = "block";
        setTimeout(SlideShow, 5000);
    }
</script>

KillerAppS2/Views/Riddle/RiddlePage.cshtml
@model KillerAppS2.ViewModel.RiddlePageModel

@{
    Layout = "~/Views/Shared/_layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <style>
        ._categories a {
            margin: 10px 4px 10px 4px;
        }
    </style>
</head>
<body>
    <div class="col-sm-10 _categories" style="margin: auto auto auto 16px; border: 2px solid black; border-radius: 5px 5px; width: 120px;">
        @foreach (var category in Model.Categories.Categories)
        {
            <div class="row">
                <a asp-controller="Riddle" asp-action="Category" asp-route-_categoryName="@category.CategoryName">@category.CategoryName</a>
            </div>
        }
    </div>
    <div class="col-sm-10" style="border: 1px solid black; margin: 20px 20px 20px 20px; width: 600px;">
        @foreach (var riddle in Model.Get.Riddles)
        {
            <div class="col-sm-10 row" style="border: 1px solid black; margin: 20px 20px 20px 20px;">
                <a class="row" onclick="SetRiddleName('@riddle.RiddleName')">@riddle.RiddleName</a>
                <a class="row">
                    @riddle.RiddleContent
                </a>

                <div id="Answer @riddle.RiddleName" style="display:none;" class="answer_list row">@riddle.Answer</div>
                <input type="button" name="answer" onclick="ShowDiv('Answer @riddle.RiddleName')" value="Show answer" />
                <div class="row">
                    @foreach (var category in riddle.Categories)
                    {
                        <a asp-controller="Riddle" asp-action="Category" asp-route-_categoryName="@category.CategoryName">@category.CategoryName</a>
                    }
                </div>
                <input class="row" type="button" name="answer" onclick="ShowDiv('Message @riddle.RiddleName')" value="Show messages" />
                <div id="Message @riddle.RiddleName" style="display:none;" class="answer_list col-sm-10 row">
                    <div class="row">
                        @foreach (var message in riddle.Messages)
                        {
                            <a class="row">@message.MessageContent</a>
                            <a class="row">@message.User.UserName</a>
                            <a class="row">@message.Time</a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
    @using Microsoft.AspNetCore.Http;
    @if (!String.IsNullOrEmpty(Context.Session.GetString("UserID")))
    {
        <div style="display:flex;justify-content:center;align-items:center;">
            <form method="post" asp-controller="Riddle" asp-action="PostMessage">
                <input asp-for="Post.UserID" value="@Context.Session.GetString("UserID")" type="hidden" />
                <input asp-for="Post.RiddleName" value="" id="riddleName" type="hidden" />
                <input asp-for="Post.Message" class="form-control" />
                <span asp-validation-for="Post.Message"></span>
                <div><input type="submit" value="Send" class="btn" /></div>
                <span asp-validation-for="Post.UserID"></span>
                <span asp-validation-for="Post.RiddleName"></span>
            </form>
        </div>
    }
</body>
</html>

<script>
    function SetRiddleName(_name) {
        document.getElementById("riddleName").value = _name;
    }

    function ShowDiv(_name) {
        var x = document.getElementById(_name);
        if (x.style.display == "none") {
            x.style.display = "";
        }
        else {
            x.style.display = "none";
        }
    }
</script>

KillerAppS2/Views/Shared/_announcements.cshtml
<style>
    ._announcementsboard {
        float: right;
        width: 250px;
        background-color: cadetblue;
        overflow: hidden;
    }

    ._boardtitle {
        font-size: 20px;
        height: 30px;
    }

    ._scroll {
        overflow: auto;
        height: 900px;
        width: 100%;
    }

    ._announcement {
        top: auto;
        left: auto;
        bottom: auto;
        right: auto;
        width: 100%;
        max-height: 500px;
    }

        ._announcement p {
            overflow: hidden;
            max-height: 400px;
        }
</style>

<div class="_announcementsboard">
    <div class="_boardtitle">Announcements</div>
    <div class="_scroll">
        <div class="_announcement">
            <header>Title</header>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas fermentum, ipsum et blandit maximus, lorem neque pretium orci, sed malesuada est lacus hendrerit nunc. Sed iaculis, dolor eget varius rhoncus, lacus mi tincidunt metus, a dignissim nisl lacus ac augue. Aliquam at ipsum nec nunc lobortis molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae dapibus eros. Suspendisse malesuada, magna vitae mattis congue, nunc nisl luctus sapien, sit amet tincidunt nulla odio a sapien. Nullam sit amet varius ipsum, id iaculis arcu.

                Quisque placerat faucibus risus non iaculis. Maecenas pharetra laoreet ligula, eget facilisis est mattis eget. Pellentesque viverra nulla et augue tempor, at posuere elit finibus. Sed velit nulla, eleifend non libero eget, semper varius est. Pellentesque sagittis tortor tortor, nec tempus massa consectetur ut. Nullam nunc dolor, venenatis vel venenatis id, finibus a nunc. Suspendisse dignissim ultrices mauris sit amet vehicula. Proin tempor, dolor id semper tristique, ante quam egestas tortor, sed semper libero felis a sapien. Donec mattis interdum enim, eget euismod tellus egestas in. Vivamus commodo, lacus ut tempus maximus, sapien lacus maximus urna, maximus convallis erat ante vitae dui. Phasellus a orci non ipsum efficitur pharetra eget non ipsum. Nam aliquam eros at lectus eleifend, non condimentum purus laoreet. Quisque a malesuada ante, vestibulum consequat massa. Curabitur non arcu sed mauris porta pharetra eu non tellus. Integer arcu lacus, rhoncus eu leo quis, volutpat fermentum urna.

                Maecenas sed vehicula lectus, eu vulputate ante. Praesent cursus quam ut arcu consequat tristique. Vivamus lobortis pellentesque mi non aliquet. Nulla vel ante rhoncus, fermentum nulla ac, vehicula ex. Sed porta urna at arcu blandit, ac scelerisque mi condimentum. Integer mauris sem, placerat sed lacus vel, venenatis maximus nisi. Duis sodales odio in tempus molestie. Aenean sit amet ipsum nulla. Cras dapibus elementum ipsum, ac bibendum tellus. Vestibulum pulvinar massa non fermentum malesuada.

                Maecenas at enim dapibus, luctus massa at, auctor sem. Praesent nec dui non mauris hendrerit tincidunt posuere in nunc. Nullam eu laoreet turpis, at sagittis ex. Donec a ligula tempor, sodales justo eu, ullamcorper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In tempus libero nec felis aliquam malesuada. Sed eu convallis dolor, sit amet dictum odio. Proin sem dolor, volutpat ut elit vitae, congue elementum purus. Vivamus elementum fringilla faucibus. Fusce cursus nulla dolor, eu commodo purus sagittis nec. Phasellus pretium ultrices tincidunt. Proin sollicitudin est vel dolor mattis, at aliquam ligula fringilla. Morbi viverra sagittis ligula, non porttitor tortor tincidunt ac. Morbi ligula justo, mattis ut finibus non, commodo ac tortor.

                Sed congue libero at elit varius, at feugiat erat tincidunt. Proin nibh justo, porttitor ut mattis vitae, laoreet et quam. Morbi eu cursus ex. Integer a pretium mi. Aenean ullamcorper, risus vel tempus accumsan, ex orci placerat ex, vel consequat tortor tellus in mauris. Curabitur vitae ex rhoncus, efficitur ex quis, facilisis justo. Donec sit amet quam sed magna viverra imperdiet. Phasellus imperdiet molestie semper. Suspendisse molestie enim eros, eu lacinia magna aliquet et. Curabitur hendrerit tincidunt volutpat. Donec feugiat arcu non nisi rutrum ornare. Vestibulum nulla magna, vestibulum non faucibus placerat, sollicitudin at dolor.
            </p>
            <p>date</p>
        </div>
        <div class="_announcement">
            <header>Title</header>
            <p>
                Lorem ipsum dolor sit amet, tempus accumsan, ex orci placerat ex, vel consequat tortor tellus in mauris. Curabitur vitae ex rhoncus, efficitur ex quis, facilisis justo. Donec sit amet quam sed magna viverra imperdiet. Phasellus imperdiet molestie semper. Suspendisse molestie enim eros, eu lacinia magna aliquet et. Curabitur hendrerit tincidunt volutpat. Donec feugiat arcu non nisi rutrum ornare. Vestibulum nulla magna, vestibulum non faucibus placerat, sollicitudin at dolor.
            </p>
            <p>date</p>
        </div>
        <div class="_announcement">
            <header>Title</header>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas fermentum, ipsum et blandit maximus, lorem neque pretium orci, sed malesuada est lacus hendrerit nunc. Sed iaculis, dolor eget varius rhoncus, lacus mi tincidunt metus, a dignissim nisl lacus ac augue. Aliquam at ipsum nec nunc lobortis molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae dapibus eros. Suspendisse malesuada, magna vitae mattis congue, nunc nisl luctus sapien, sit amet tincidunt nulla odio a sapien. Nullam sit amet varius ipsum, id iaculis arcu.

                Quisque placerat faucibus risus non iaculis. Maecenas pharetra laoreet ligula, eget facilisis est mattis eget. Pellentesque viverra nulla et augue tempor, at posuere elit finibus. Sed velit nulla, eleifend non libero eget, semper varius est. Pellentesque sagittis tortor tortor, nec tempus massa consectetur ut. Nullam nunc dolor, venenatis vel venenatis id, finibus a nunc. Suspendisse dignissim ultrices mauris sit amet vehicula. Proin tempor, dolor id semper tristique, ante quam egestas tortor, sed semper libero felis a sapien. Donec mattis interdum enim, eget euismod tellus egestas in. Vivamus commodo, lacus ut tempus maximus, sapien lacus maximus urna, maximus convallis erat ante vitae dui. Phasellus a orci non ipsum efficitur pharetra eget non ipsum. Nam aliquam eros at lectus eleifend, non condimentum purus laoreet. Quisque a malesuada ante, vestibulum consequat massa. Curabitur non arcu sed mauris porta pharetra eu non tellus. Integer arcu lacus, rhoncus eu leo quis, volutpat fermentum urna.

                Maecenas sed vehicula lectus, eu vulputate ante. Praesent cursus quam ut arcu consequat tristique. Vivamus lobortis pellentesque mi non aliquet. Nulla vel ante rhoncus, fermentum nulla ac, vehicula ex. Sed porta urna at arcu blandit, ac scelerisque mi condimentum. Integer mauris sem, placerat sed lacus vel, venenatis maximus nisi. Duis sodales odio in tempus molestie. Aenean sit amet ipsum nulla. Cras dapibus elementum ipsum, ac bibendum tellus. Vestibulum pulvinar massa non fermentum malesuada.

                Maecenas at enim dapibus, luctus massa at, auctor sem. Praesent nec dui non mauris hendrerit tincidunt posuere in nunc. Nullam eu laoreet turpis, at sagittis ex. Donec a ligula tempor, sodales justo eu, ullamcorper risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In tempus libero nec felis aliquam malesuada. Sed eu convallis dolor, sit amet dictum odio. Proin sem dolor, volutpat ut elit vitae, congue elementum purus. Vivamus elementum fringilla faucibus. Fusce cursus nulla dolor, eu commodo purus sagittis nec. Phasellus pretium ultrices tincidunt. Proin sollicitudin est vel dolor mattis, at aliquam ligula fringilla. Morbi viverra sagittis ligula, non porttitor tortor tincidunt ac. Morbi ligula justo, mattis ut finibus non, commodo ac tortor.

                Sed congue libero at elit varius, at feugiat erat tincidunt. Proin nibh justo, porttitor ut mattis vitae, laoreet et quam. Morbi eu cursus ex. Integer a pretium mi. Aenean ullamcorper, risus vel tempus accumsan, ex orci placerat ex, vel consequat tortor tellus in mauris. Curabitur vitae ex rhoncus, efficitur ex quis, facilisis justo. Donec sit amet quam sed magna viverra imperdiet. Phasellus imperdiet molestie semper. Suspendisse molestie enim eros, eu lacinia magna aliquet et. Curabitur hendrerit tincidunt volutpat. Donec feugiat arcu non nisi rutrum ornare. Vestibulum nulla magna, vestibulum non faucibus placerat, sollicitudin at dolor.
            </p>
            <p>date</p>
        </div>
    </div>
</div>

KillerAppS2/Views/Shared/_categories.cshtml
<style>
    ._categoryboard {
        background-color: #00ff21;
        width: 250px;
        overflow: hidden;
    }

    ._categories {
        float: left;
        height: 900px;
        overflow: auto;
        width: 250px;
        overflow-x: hidden;
    }

    ._category {
        color: black;
        margin-bottom: 4px;
        font-size: 15px;
        height: 25px;
        width: 250px;
    }
</style>
<div class="_categoryboard">
    <div class="_boardtitle">Categories</div>
    <div class="_categories">
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
        <div class="_category">category</div>
    </div>
</div>

KillerAppS2/Views/Shared/_layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style>
        ._nav {
            background-color: crimson;
        }

            ._nav a {
                font-size: 20px;
                margin: 18px 4px 4px 16px;
                color: black;
            }

                ._nav a:hover {
                    background-color: chocolate;
                }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="row col-lg-12 navbar-fixed-top _nav">
        <a asp-controller="Home" asp-action="Index">RiddleForm</a>
        @using Microsoft.AspNetCore.Http;
        @if (String.IsNullOrEmpty(Context.Session.GetString("UserID")))
        {
            <a asp-controller="User" asp-action="LogIn">LogIn</a>
        }
        else
        {
            <a>@Context.Session.GetString("UserName")</a>
            <a asp-controller="User" asp-action="LogOut">LogOut</a>
        }
    </div>
    <div class="col-sm-10 row">
        @RenderBody()
    </div>
</body>
</html>

KillerAppS2/Views/User/LogIn.cshtml
@model ServiceLayer.ViewModels.InputViewModels.LogInModel

@{
    Layout = "~/Views/Shared/_layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <style>
    </style>
</head>
<body>
    <div style="display:flex;justify-content:center;align-items:center;">
        <form method="post" class="col-sm-10" style="width: 350px;">
            <h2 class="row">Login</h2>
            <input asp-for="Username" class="form-control row" style="width: 300px;">
            <span asp-validation-for="Username" class="row" style="width: 300px;"></span>
            <input asp-for="Password" class="form-control row" style="width: 300px;">
            <span asp-validation-for="Password" class="row" style="width: 300px;"></span>
            <div><input type="submit" value="Login" class="btn row" style="width: 300px;" /></div>
            <a asp-controller="User" asp-action="AddUser" class="row" style="width: 300px;">Create Account</a>
        </form>
    </div>
</body>
</html>